[global]
developmentMode = false

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
runOnSave = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#0A0A0A"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "Montserrat"

[logger]
level = "info"

[client]
caching = true
displayEnabled = true
showErrorDetails = true

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true
